package com.clock.zc.punchtheclock.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLOCK_HISTORY".
*/
public class ClockHistoryDao extends AbstractDao<ClockHistory, Void> {

    public static final String TABLENAME = "CLOCK_HISTORY";

    /**
     * Properties of entity ClockHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Time = new Property(0, String.class, "time", false, "TIME");
        public final static Property Statue = new Property(1, int.class, "statue", false, "STATUE");
    }


    public ClockHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public ClockHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLOCK_HISTORY\" (" + //
                "\"TIME\" TEXT," + // 0: time
                "\"STATUE\" INTEGER NOT NULL );"); // 1: statue
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLOCK_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClockHistory entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
        stmt.bindLong(2, entity.getStatue());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClockHistory entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
        stmt.bindLong(2, entity.getStatue());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ClockHistory readEntity(Cursor cursor, int offset) {
        ClockHistory entity = new ClockHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // time
            cursor.getInt(offset + 1) // statue
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClockHistory entity, int offset) {
        entity.setTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStatue(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ClockHistory entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ClockHistory entity) {
        return null;
    }

    @Override
    public boolean hasKey(ClockHistory entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
