//package com.clock.zc.punchtheclock.bean;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import com.clock.zc.punchtheclock.bean.ClockHistory;
//
//import com.clock.zc.punchtheclock.bean.ClockHistoryDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig clockHistoryDaoConfig;
//
//    private final ClockHistoryDao clockHistoryDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        clockHistoryDaoConfig = daoConfigMap.get(ClockHistoryDao.class).clone();
//        clockHistoryDaoConfig.initIdentityScope(type);
//
//        clockHistoryDao = new ClockHistoryDao(clockHistoryDaoConfig, this);
//
//        registerDao(ClockHistory.class, clockHistoryDao);
//    }
//
//    public void clear() {
//        clockHistoryDaoConfig.clearIdentityScope();
//    }
//
//    public ClockHistoryDao getClockHistoryDao() {
//        return clockHistoryDao;
//    }
//
//}
